CREATE TABLE `book` (
  `id` bigint(20) NOT NULL,
  `title_en` varchar(255) COLLATE BINARY DEFAULT NULL,
  `slug_en` varchar(255) COLLATE BINARY DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `slug_es` varchar(255) COLLATE BINARY DEFAULT NULL,
  `title_es` varchar(255) COLLATE BINARY DEFAULT NULL,
  `slug_fa` varchar(255) COLLATE BINARY DEFAULT NULL,
  `title_fa` varchar(255) COLLATE BINARY DEFAULT NULL,
  `slug_hi` varchar(255) COLLATE BINARY DEFAULT NULL,
  `title_hi` varchar(255) COLLATE BINARY DEFAULT NULL,
  `slug_pt` varchar(255) COLLATE BINARY DEFAULT NULL,
  `title_pt` varchar(255) COLLATE BINARY DEFAULT NULL,
  `slug_sv` varchar(255) COLLATE BINARY DEFAULT NULL,
  `title_sv` varchar(255) COLLATE BINARY DEFAULT NULL,
  `slug_de` varchar(255) COLLATE BINARY DEFAULT NULL,
  `title_de` varchar(255) COLLATE BINARY DEFAULT NULL,
  PRIMARY KEY (`id`)
);